##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://isuu00001library102stg.z21.web.core.windows.net
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /collections/underwood
# location of code, the full url to your github repository
source-code: https://github.com/isu-digital/digital-collections-template

# url to the shared assets folder on mainweb
digital-assets: https://isuu00001library102stg.z21.web.core.windows.net/assets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Sarah Underwood Papers
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of letters and other materials documenting life in 19th century Iowa
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Sarah Tefft married Horace Underwood on November 30, 1851 in Kingston, Rhode Island. Within a few years, the couple would move to eastern Iowa, near the town of Princeton. The pair had a daughter, Mary Lilian in 1859. In the early 1860s, they returned to Rhode Island. This collection includes letters detailing Sarah's life in Iowa, asking after family and friends in Rhode Island, pressed flowers, a photograph, and a mourning shroud sample."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: iowa; 19th century; midwest; handwritten letters
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: lsulli12

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: underwood
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
page_gen:
  - data: 'underwood'
  - data: 'underwood-iiif'
    template: 'manifest'
    template_override: true
    name: 'objectid'
    dir: 'manifests'
    extension: 'json' 
    filter: 'objectid'

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Iowa State University Library Digital Collections"
organization-link: https://www.lib.iastate.edu/
organization-logo-banner: https://isuu00001library102stg.z21.web.core.windows.net/assets/media/ISU_Library_Center_Red.png
organization-logo-nav: https://isuu00001library102stg.z21.web.core.windows.net/assets/media/ISU_Library_Center_White.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
